version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_SQS_ENDPOINT=http://localstack:4566
    depends_on:
      - redis
      - localstack
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
